name: bucket_publish
on:
  push:
    branches:
      - master
jobs:
  bucket_publish:
    env:
      BUCKET_NAME: 'laboiteadons-org'
      GENERATE_SOURCEMAP: false
    runs-on: ubuntu-latest
    name: Create a Textile Bucket
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Bucket push action
      id: push
      uses: textileio/github-action-bucket-push@master
      with:
        bucket-name: '${{ env.BUCKET_NAME }}'
        path: 'index.html'
        token: ${{ secrets.TEXTILE_AUTH_TOKEN }}
    - name: Get the output CID
      run: echo "The CID was ${{ steps.push.outputs.cid }}"
    - name: Get the Bucket URL
      run: echo "The Bucket URL is ${{ steps.push.outputs.url }}"